name: Self-Hosted CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Ajout d'un déclencheur manuel pour faciliter les tests
  workflow_dispatch:

jobs:
  build-and-test:
    # Spécifie d'utiliser votre runner auto-hébergé au lieu des runners GitHub
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log Node.js version
      run: node --version

    - name: Cache node modules
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-


    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install --force

    - name: Run tests
      run: export CHROME_BIN=/usr/bin/chromium && npm test -- --watch=false --browsers=ChromeHeadless --no-progress

    - name: Build application
      run: npm run build -- --configuration production
